---
title: "DATS 6101 Spring 2020 Olympic Data EDA"
author: "Izzy Illari"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    keep_tex: yes
    number_sections: no
    theme: readable
    toc: yes
    toc_depth: '2'
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = F, results = T, message = F)
options(scientific=T, digits = 3) 
```

```{r basic, include=F}
loadPkg = function(pkg, character.only = FALSE) { 
  if (!character.only) { pkg <- as.character(substitute(pkg)) }
  if (!require(pkg,character.only=T, quietly =T)) {  install.packages(pkg,dep=T,repos="http://cran.us.r-project.org"); if(!require(pkg,character.only=T)) stop("Package not found") } 
}
loadPkg(knitr)

unloadPkg = function(pkg, character.only = FALSE) { 
  if(!character.only) { pkg <- as.character(substitute(pkg)) } 
  search_item <- paste("package", pkg,sep = ":") 
  while(search_item %in% search()) { detach(search_item, unload = TRUE, character.only = TRUE) } 
}
```

```{r packages, echo=F, include=F}
library(ggplot2)
require(gridExtra)
```

```{r data, echo=F}
#Data taken from https://www.kaggle.com/heesoo37/120-years-of-olympic-history-athletes-and-results
athlete_events <- data.frame(read.csv("/Users/iillari/Documents/gwu/spring2020/intro_dats/eda_project/120-years-of-olympic-history-athletes-and-results/athlete_events.csv"))
noc_regions <- data.frame(read.csv("/Users/iillari/Documents/gwu/spring2020/intro_dats/eda_project/120-years-of-olympic-history-athletes-and-results/noc_regions.csv"))
#omit NA data
athlete_events_noNA <- na.omit(athlete_events)
#create lists to hold data
data_year <- split(athlete_events_noNA, athlete_events_noNA$Year)
years <- names(data_year)
list_year <- list(1896, 1900, 1904, 1906, 1908, 1912, 1920, 1924, 1928, 1932, 1936, 1948, 1952, 1956, 1960, 1964, 1968, 1972, 1976, 1980, 1984, 1988, 1992, 1994, 1996, 1998, 2000, 2002, 2004, 2006, 2008, 2010, 2012, 2014, 2016)
mean_years_weight <- list()
sd_years_weight <- list()
#split data by sport 
data_sport <- split(athlete_events_noNA, athlete_events_noNA$Sport)
sport_names2 <- names(data_sport)
#factor sports
athlete_events_noNA$Sport <- as.factor(athlete_events_noNA$Sport)
sport_names <- unique(athlete_events_noNA$Sport) 
sport_names <- sort(sport_names, decreasing = FALSE)
string_sports <- list()
for (i in 1:length(sport_names)) {
  string_sports[[i]] <- toString(sport_names[[i]])
}
```

# Top Ten Events

**Here are the top ten events in the Olympics**

```{r top_ten, echo=F}
list_sports <- as.data.frame(table(athlete_events_noNA$Sport))[1]
sport_counts <- as.data.frame(table(athlete_events_noNA$Sport))[2]
count_sports_data <- do.call(rbind, Map(data.frame, "sport.names" = list_sports, "sport.counts" = sport_counts))
sort_count_sports_data <- count_sports_data[order(-count_sports_data$sport.counts),]
sort_count_sports_data[2:11,]
top10 <- sort_count_sports_data[2:11,][1]
```

I'm going to look at these top 10 events over all the years.

```{r over_time, echo=F}
# Swimming
data_Swimming_gender <- split(data_sport$Swimming, data_sport$Swimming$Sex)
data_Swimming_F_year <- split(data_Swimming_gender$F, data_Swimming_gender$F$Year)
data_Swimming_M_year <- split(data_Swimming_gender$"M", data_Swimming_gender$"M"$Year)
years_F_Swimming <- names(data_Swimming_F_year)
years_M_Swimming <- names(data_Swimming_M_year)
mean_years_weight_F_Swimming <- list()
sd_years_weight_F_Swimming <- list()
mean_years_height_F_Swimming <- list()
sd_years_height_F_Swimming <- list()
mean_years_weight_M_Swimming <- list()
sd_years_weight_M_Swimming <- list()
mean_years_height_M_Swimming <- list()
sd_years_height_M_Swimming <- list()
# women data
for (i in 1:length(data_Swimming_F_year)) {
	mean_years_weight_F_Swimming[[i]] <- mean(data_Swimming_F_year[[i]]$Weight)
	sd_years_weight_F_Swimming[[i]] <- sd(data_Swimming_F_year[[i]]$Weight)
	mean_years_height_F_Swimming[[i]] <- mean(data_Swimming_F_year[[i]]$Height)
	sd_years_height_F_Swimming[[i]] <- sd(data_Swimming_F_year[[i]]$Height)
}
# men data
for (i in 1:length(data_Swimming_M_year)) {
	mean_years_weight_M_Swimming[[i]] <- mean(data_Swimming_M_year[[i]]$Weight)
	sd_years_weight_M_Swimming[[i]] <- sd(data_Swimming_M_year[[i]]$Weight)
	mean_years_height_M_Swimming[[i]] <- mean(data_Swimming_M_year[[i]]$Height)
	sd_years_height_M_Swimming[[i]] <- sd(data_Swimming_M_year[[i]]$Height)
}
# make data frames
Swimming_F_data <- do.call(rbind, Map(data.frame, Year = years_F_Swimming, Mean_Weight = mean_years_weight_F_Swimming, StdDev_Weight = sd_years_weight_F_Swimming, Mean_Height = mean_years_height_F_Swimming, StdDev_Height = sd_years_height_F_Swimming))
Swimming_M_data <- do.call(rbind, Map(data.frame, Year = years_M_Swimming, Mean_Weight = mean_years_weight_F_Swimming, StdDev_Weight = sd_years_weight_F_Swimming, Mean_Height = mean_years_height_F_Swimming, StdDev_Height = sd_years_height_F_Swimming))
# Rowing
data_Rowing_gender <- split(data_sport$Rowing, data_sport$Rowing$Sex)
data_Rowing_F_year <- split(data_Rowing_gender$F, data_Rowing_gender$F$Year)
data_Rowing_M_year <- split(data_Rowing_gender$"M", data_Rowing_gender$"M"$Year)
years_F_Rowing <- names(data_Rowing_F_year)
years_M_Rowing <- names(data_Rowing_M_year)
mean_years_weight_F_Rowing <- list()
sd_years_weight_F_Rowing <- list()
mean_years_height_F_Rowing <- list()
sd_years_height_F_Rowing <- list()
mean_years_weight_M_Rowing <- list()
sd_years_weight_M_Rowing <- list()
mean_years_height_M_Rowing <- list()
sd_years_height_M_Rowing <- list()
# women data
for (i in 1:length(data_Rowing_F_year)) {
	mean_years_weight_F_Rowing[[i]] <- mean(data_Rowing_F_year[[i]]$Weight)
	sd_years_weight_F_Rowing[[i]] <- sd(data_Rowing_F_year[[i]]$Weight)
	mean_years_height_F_Rowing[[i]] <- mean(data_Rowing_F_year[[i]]$Height)
	sd_years_height_F_Rowing[[i]] <- sd(data_Rowing_F_year[[i]]$Height)
}
# men data
for (i in 1:length(data_Rowing_M_year)) {
	mean_years_weight_M_Rowing[[i]] <- mean(data_Rowing_M_year[[i]]$Weight)
	sd_years_weight_M_Rowing[[i]] <- sd(data_Rowing_M_year[[i]]$Weight)
	mean_years_height_M_Rowing[[i]] <- mean(data_Rowing_M_year[[i]]$Height)
	sd_years_height_M_Rowing[[i]] <- sd(data_Rowing_M_year[[i]]$Height)
}
# make data frames
Rowing_F_data <- do.call(rbind, Map(data.frame, Year = years_F_Rowing, Mean_Weight = mean_years_weight_F_Rowing, StdDev_Weight = sd_years_weight_F_Rowing, Mean_Height = mean_years_height_F_Rowing, StdDev_Height = sd_years_height_F_Rowing))
Rowing_M_data <- do.call(rbind, Map(data.frame, Year = years_M_Rowing, Mean_Weight = mean_years_weight_F_Rowing, StdDev_Weight = sd_years_weight_F_Rowing, Mean_Height = mean_years_height_F_Rowing, StdDev_Height = sd_years_height_F_Rowing))
# Ice.Hockey
data_Ice.Hockey_gender <- split(data_sport$"Ice Hockey", data_sport$"Ice Hockey"$Sex)
data_Ice.Hockey_F_year <- split(data_Ice.Hockey_gender$F, data_Ice.Hockey_gender$F$Year)
data_Ice.Hockey_M_year <- split(data_Ice.Hockey_gender$"M", data_Ice.Hockey_gender$"M"$Year)
years_F_Ice.Hockey <- names(data_Ice.Hockey_F_year)
years_M_Ice.Hockey <- names(data_Ice.Hockey_M_year)
mean_years_weight_F_Ice.Hockey <- list()
sd_years_weight_F_Ice.Hockey <- list()
mean_years_height_F_Ice.Hockey <- list()
sd_years_height_F_Ice.Hockey <- list()
mean_years_weight_M_Ice.Hockey <- list()
sd_years_weight_M_Ice.Hockey <- list()
mean_years_height_M_Ice.Hockey <- list()
sd_years_height_M_Ice.Hockey <- list()
# women data
for (i in 1:length(data_Ice.Hockey_F_year)) {
	mean_years_weight_F_Ice.Hockey[[i]] <- mean(data_Ice.Hockey_F_year[[i]]$Weight)
	sd_years_weight_F_Ice.Hockey[[i]] <- sd(data_Ice.Hockey_F_year[[i]]$Weight)
	mean_years_height_F_Ice.Hockey[[i]] <- mean(data_Ice.Hockey_F_year[[i]]$Height)
	sd_years_height_F_Ice.Hockey[[i]] <- sd(data_Ice.Hockey_F_year[[i]]$Height)
}
# men data
for (i in 1:length(data_Ice.Hockey_M_year)) {
	mean_years_weight_M_Ice.Hockey[[i]] <- mean(data_Ice.Hockey_M_year[[i]]$Weight)
	sd_years_weight_M_Ice.Hockey[[i]] <- sd(data_Ice.Hockey_M_year[[i]]$Weight)
	mean_years_height_M_Ice.Hockey[[i]] <- mean(data_Ice.Hockey_M_year[[i]]$Height)
	sd_years_height_M_Ice.Hockey[[i]] <- sd(data_Ice.Hockey_M_year[[i]]$Height)
}
# make data frames
Ice.Hockey_F_data <- do.call(rbind, Map(data.frame, Year = years_F_Ice.Hockey, Mean_Weight = mean_years_weight_F_Ice.Hockey, StdDev_Weight = sd_years_weight_F_Ice.Hockey, Mean_Height = mean_years_height_F_Ice.Hockey, StdDev_Height = sd_years_height_F_Ice.Hockey))
Ice.Hockey_M_data <- do.call(rbind, Map(data.frame, Year = years_M_Ice.Hockey, Mean_Weight = mean_years_weight_F_Ice.Hockey, StdDev_Weight = sd_years_weight_F_Ice.Hockey, Mean_Height = mean_years_height_F_Ice.Hockey, StdDev_Height = sd_years_height_F_Ice.Hockey))
# Hockey
data_Hockey_gender <- split(data_sport$Hockey, data_sport$Hockey$Sex)
data_Hockey_F_year <- split(data_Hockey_gender$F, data_Hockey_gender$F$Year)
data_Hockey_M_year <- split(data_Hockey_gender$"M", data_Hockey_gender$"M"$Year)
years_F_Hockey <- names(data_Hockey_F_year)
years_M_Hockey <- names(data_Hockey_M_year)
mean_years_weight_F_Hockey <- list()
sd_years_weight_F_Hockey <- list()
mean_years_height_F_Hockey <- list()
sd_years_height_F_Hockey <- list()
mean_years_weight_M_Hockey <- list()
sd_years_weight_M_Hockey <- list()
mean_years_height_M_Hockey <- list()
sd_years_height_M_Hockey <- list()
# women data
for (i in 1:length(data_Hockey_F_year)) {
	mean_years_weight_F_Hockey[[i]] <- mean(data_Hockey_F_year[[i]]$Weight)
	sd_years_weight_F_Hockey[[i]] <- sd(data_Hockey_F_year[[i]]$Weight)
	mean_years_height_F_Hockey[[i]] <- mean(data_Hockey_F_year[[i]]$Height)
	sd_years_height_F_Hockey[[i]] <- sd(data_Hockey_F_year[[i]]$Height)
}
# men data
for (i in 1:length(data_Hockey_M_year)) {
	mean_years_weight_M_Hockey[[i]] <- mean(data_Hockey_M_year[[i]]$Weight)
	sd_years_weight_M_Hockey[[i]] <- sd(data_Hockey_M_year[[i]]$Weight)
	mean_years_height_M_Hockey[[i]] <- mean(data_Hockey_M_year[[i]]$Height)
	sd_years_height_M_Hockey[[i]] <- sd(data_Hockey_M_year[[i]]$Height)
}
# make data frames
Hockey_F_data <- do.call(rbind, Map(data.frame, Year = years_F_Hockey, Mean_Weight = mean_years_weight_F_Hockey, StdDev_Weight = sd_years_weight_F_Hockey, Mean_Height = mean_years_height_F_Hockey, StdDev_Height = sd_years_height_F_Hockey))
Hockey_M_data <- do.call(rbind, Map(data.frame, Year = years_M_Hockey, Mean_Weight = mean_years_weight_F_Hockey, StdDev_Weight = sd_years_weight_F_Hockey, Mean_Height = mean_years_height_F_Hockey, StdDev_Height = sd_years_height_F_Hockey))
# Gymnastics
data_Gymnastics_gender <- split(data_sport$Gymnastics, data_sport$Gymnastics$Sex)
data_Gymnastics_F_year <- split(data_Gymnastics_gender$F, data_Gymnastics_gender$F$Year)
data_Gymnastics_M_year <- split(data_Gymnastics_gender$"M", data_Gymnastics_gender$"M"$Year)
years_F_Gymnastics <- names(data_Gymnastics_F_year)
years_M_Gymnastics <- names(data_Gymnastics_M_year)
mean_years_weight_F_Gymnastics <- list()
sd_years_weight_F_Gymnastics <- list()
mean_years_height_F_Gymnastics <- list()
sd_years_height_F_Gymnastics <- list()
mean_years_weight_M_Gymnastics <- list()
sd_years_weight_M_Gymnastics <- list()
mean_years_height_M_Gymnastics <- list()
sd_years_height_M_Gymnastics <- list()
# women data
for (i in 1:length(data_Gymnastics_F_year)) {
	mean_years_weight_F_Gymnastics[[i]] <- mean(data_Gymnastics_F_year[[i]]$Weight)
	sd_years_weight_F_Gymnastics[[i]] <- sd(data_Gymnastics_F_year[[i]]$Weight)
	mean_years_height_F_Gymnastics[[i]] <- mean(data_Gymnastics_F_year[[i]]$Height)
	sd_years_height_F_Gymnastics[[i]] <- sd(data_Gymnastics_F_year[[i]]$Height)
}
# men data
for (i in 1:length(data_Gymnastics_M_year)) {
	mean_years_weight_M_Gymnastics[[i]] <- mean(data_Gymnastics_M_year[[i]]$Weight)
	sd_years_weight_M_Gymnastics[[i]] <- sd(data_Gymnastics_M_year[[i]]$Weight)
	mean_years_height_M_Gymnastics[[i]] <- mean(data_Gymnastics_M_year[[i]]$Height)
	sd_years_height_M_Gymnastics[[i]] <- sd(data_Gymnastics_M_year[[i]]$Height)
}
# make data frames
Gymnastics_F_data <- do.call(rbind, Map(data.frame, Year = years_F_Gymnastics, Mean_Weight = mean_years_weight_F_Gymnastics, StdDev_Weight = sd_years_weight_F_Gymnastics, Mean_Height = mean_years_height_F_Gymnastics, StdDev_Height = sd_years_height_F_Gymnastics))
Gymnastics_M_data <- do.call(rbind, Map(data.frame, Year = years_M_Gymnastics, Mean_Weight = mean_years_weight_F_Gymnastics, StdDev_Weight = sd_years_weight_F_Gymnastics, Mean_Height = mean_years_height_F_Gymnastics, StdDev_Height = sd_years_height_F_Gymnastics))
# Fencing
data_Fencing_gender <- split(data_sport$Fencing, data_sport$Fencing$Sex)
data_Fencing_F_year <- split(data_Fencing_gender$F, data_Fencing_gender$F$Year)
data_Fencing_M_year <- split(data_Fencing_gender$"M", data_Fencing_gender$"M"$Year)
years_F_Fencing <- names(data_Fencing_F_year)
years_M_Fencing <- names(data_Fencing_M_year)
mean_years_weight_F_Fencing <- list()
sd_years_weight_F_Fencing <- list()
mean_years_height_F_Fencing <- list()
sd_years_height_F_Fencing <- list()
mean_years_weight_M_Fencing <- list()
sd_years_weight_M_Fencing <- list()
mean_years_height_M_Fencing <- list()
sd_years_height_M_Fencing <- list()
# women data
for (i in 1:length(data_Fencing_F_year)) {
	mean_years_weight_F_Fencing[[i]] <- mean(data_Fencing_F_year[[i]]$Weight)
	sd_years_weight_F_Fencing[[i]] <- sd(data_Fencing_F_year[[i]]$Weight)
	mean_years_height_F_Fencing[[i]] <- mean(data_Fencing_F_year[[i]]$Height)
	sd_years_height_F_Fencing[[i]] <- sd(data_Fencing_F_year[[i]]$Height)
}
# men data
for (i in 1:length(data_Fencing_M_year)) {
	mean_years_weight_M_Fencing[[i]] <- mean(data_Fencing_M_year[[i]]$Weight)
	sd_years_weight_M_Fencing[[i]] <- sd(data_Fencing_M_year[[i]]$Weight)
	mean_years_height_M_Fencing[[i]] <- mean(data_Fencing_M_year[[i]]$Height)
	sd_years_height_M_Fencing[[i]] <- sd(data_Fencing_M_year[[i]]$Height)
}
# make data frames
Fencing_F_data <- do.call(rbind, Map(data.frame, Year = years_F_Fencing, Mean_Weight = mean_years_weight_F_Fencing, StdDev_Weight = sd_years_weight_F_Fencing, Mean_Height = mean_years_height_F_Fencing, StdDev_Height = sd_years_height_F_Fencing))
Fencing_M_data <- do.call(rbind, Map(data.frame, Year = years_M_Fencing, Mean_Weight = mean_years_weight_F_Fencing, StdDev_Weight = sd_years_weight_F_Fencing, Mean_Height = mean_years_height_F_Fencing, StdDev_Height = sd_years_height_F_Fencing))
# Football
data_Football_gender <- split(data_sport$Football, data_sport$Football$Sex)
data_Football_F_year <- split(data_Football_gender$F, data_Football_gender$F$Year)
data_Football_M_year <- split(data_Football_gender$"M", data_Football_gender$"M"$Year)
years_F_Football <- names(data_Football_F_year)
years_M_Football <- names(data_Football_M_year)
mean_years_weight_F_Football <- list()
sd_years_weight_F_Football <- list()
mean_years_height_F_Football <- list()
sd_years_height_F_Football <- list()
mean_years_weight_M_Football <- list()
sd_years_weight_M_Football <- list()
mean_years_height_M_Football <- list()
sd_years_height_M_Football <- list()
# women data
for (i in 1:length(data_Football_F_year)) {
	mean_years_weight_F_Football[[i]] <- mean(data_Football_F_year[[i]]$Weight)
	sd_years_weight_F_Football[[i]] <- sd(data_Football_F_year[[i]]$Weight)
	mean_years_height_F_Football[[i]] <- mean(data_Football_F_year[[i]]$Height)
	sd_years_height_F_Football[[i]] <- sd(data_Football_F_year[[i]]$Height)
}
# men data
for (i in 1:length(data_Football_M_year)) {
	mean_years_weight_M_Football[[i]] <- mean(data_Football_M_year[[i]]$Weight)
	sd_years_weight_M_Football[[i]] <- sd(data_Football_M_year[[i]]$Weight)
	mean_years_height_M_Football[[i]] <- mean(data_Football_M_year[[i]]$Height)
	sd_years_height_M_Football[[i]] <- sd(data_Football_M_year[[i]]$Height)
}
# make data frames
Football_F_data <- do.call(rbind, Map(data.frame, Year = years_F_Football, Mean_Weight = mean_years_weight_F_Football, StdDev_Weight = sd_years_weight_F_Football, Mean_Height = mean_years_height_F_Football, StdDev_Height = sd_years_height_F_Football))
Football_M_data <- do.call(rbind, Map(data.frame, Year = years_M_Football, Mean_Weight = mean_years_weight_F_Football, StdDev_Weight = sd_years_weight_F_Football, Mean_Height = mean_years_height_F_Football, StdDev_Height = sd_years_height_F_Football))
# Canoeing
data_Canoeing_gender <- split(data_sport$Canoeing, data_sport$Canoeing$Sex)
data_Canoeing_F_year <- split(data_Canoeing_gender$F, data_Canoeing_gender$F$Year)
data_Canoeing_M_year <- split(data_Canoeing_gender$"M", data_Canoeing_gender$"M"$Year)
years_F_Canoeing <- names(data_Canoeing_F_year)
years_M_Canoeing <- names(data_Canoeing_M_year)
mean_years_weight_F_Canoeing <- list()
sd_years_weight_F_Canoeing <- list()
mean_years_height_F_Canoeing <- list()
sd_years_height_F_Canoeing <- list()
mean_years_weight_M_Canoeing <- list()
sd_years_weight_M_Canoeing <- list()
mean_years_height_M_Canoeing <- list()
sd_years_height_M_Canoeing <- list()
# women data
for (i in 1:length(data_Canoeing_F_year)) {
	mean_years_weight_F_Canoeing[[i]] <- mean(data_Canoeing_F_year[[i]]$Weight)
	sd_years_weight_F_Canoeing[[i]] <- sd(data_Canoeing_F_year[[i]]$Weight)
	mean_years_height_F_Canoeing[[i]] <- mean(data_Canoeing_F_year[[i]]$Height)
	sd_years_height_F_Canoeing[[i]] <- sd(data_Canoeing_F_year[[i]]$Height)
}
# men data
for (i in 1:length(data_Canoeing_M_year)) {
	mean_years_weight_M_Canoeing[[i]] <- mean(data_Canoeing_M_year[[i]]$Weight)
	sd_years_weight_M_Canoeing[[i]] <- sd(data_Canoeing_M_year[[i]]$Weight)
	mean_years_height_M_Canoeing[[i]] <- mean(data_Canoeing_M_year[[i]]$Height)
	sd_years_height_M_Canoeing[[i]] <- sd(data_Canoeing_M_year[[i]]$Height)
}
# make data frames
Canoeing_F_data <- do.call(rbind, Map(data.frame, Year = years_F_Canoeing, Mean_Weight = mean_years_weight_F_Canoeing, StdDev_Weight = sd_years_weight_F_Canoeing, Mean_Height = mean_years_height_F_Canoeing, StdDev_Height = sd_years_height_F_Canoeing))
Canoeing_M_data <- do.call(rbind, Map(data.frame, Year = years_M_Canoeing, Mean_Weight = mean_years_weight_F_Canoeing, StdDev_Weight = sd_years_weight_F_Canoeing, Mean_Height = mean_years_height_F_Canoeing, StdDev_Height = sd_years_height_F_Canoeing))
# Basketball
data_Basketball_gender <- split(data_sport$Basketball, data_sport$Basketball$Sex)
data_Basketball_F_year <- split(data_Basketball_gender$F, data_Basketball_gender$F$Year)
data_Basketball_M_year <- split(data_Basketball_gender$"M", data_Basketball_gender$"M"$Year)
years_F_Basketball <- names(data_Basketball_F_year)
years_M_Basketball <- names(data_Basketball_M_year)
mean_years_weight_F_Basketball <- list()
sd_years_weight_F_Basketball <- list()
mean_years_height_F_Basketball <- list()
sd_years_height_F_Basketball <- list()
mean_years_weight_M_Basketball <- list()
sd_years_weight_M_Basketball <- list()
mean_years_height_M_Basketball <- list()
sd_years_height_M_Basketball <- list()
# women data
for (i in 1:length(data_Basketball_F_year)) {
	mean_years_weight_F_Basketball[[i]] <- mean(data_Basketball_F_year[[i]]$Weight)
	sd_years_weight_F_Basketball[[i]] <- sd(data_Basketball_F_year[[i]]$Weight)
	mean_years_height_F_Basketball[[i]] <- mean(data_Basketball_F_year[[i]]$Height)
	sd_years_height_F_Basketball[[i]] <- sd(data_Basketball_F_year[[i]]$Height)
}
# men data
for (i in 1:length(data_Basketball_M_year)) {
	mean_years_weight_M_Basketball[[i]] <- mean(data_Basketball_M_year[[i]]$Weight)
	sd_years_weight_M_Basketball[[i]] <- sd(data_Basketball_M_year[[i]]$Weight)
	mean_years_height_M_Basketball[[i]] <- mean(data_Basketball_M_year[[i]]$Height)
	sd_years_height_M_Basketball[[i]] <- sd(data_Basketball_M_year[[i]]$Height)
}
# make data frames
Basketball_F_data <- do.call(rbind, Map(data.frame, Year = years_F_Basketball, Mean_Weight = mean_years_weight_F_Basketball, StdDev_Weight = sd_years_weight_F_Basketball, Mean_Height = mean_years_height_F_Basketball, StdDev_Height = sd_years_height_F_Basketball))
Basketball_M_data <- do.call(rbind, Map(data.frame, Year = years_M_Basketball, Mean_Weight = mean_years_weight_F_Basketball, StdDev_Weight = sd_years_weight_F_Basketball, Mean_Height = mean_years_height_F_Basketball, StdDev_Height = sd_years_height_F_Basketball))
# Wrestling
data_Wrestling_gender <- split(data_sport$Wrestling, data_sport$Wrestling$Sex)
data_Wrestling_F_year <- split(data_Wrestling_gender$F, data_Wrestling_gender$F$Year)
data_Wrestling_M_year <- split(data_Wrestling_gender$"M", data_Wrestling_gender$"M"$Year)
years_F_Wrestling <- names(data_Wrestling_F_year)
years_M_Wrestling <- names(data_Wrestling_M_year)
mean_years_weight_F_Wrestling <- list()
sd_years_weight_F_Wrestling <- list()
mean_years_height_F_Wrestling <- list()
sd_years_height_F_Wrestling <- list()
mean_years_weight_M_Wrestling <- list()
sd_years_weight_M_Wrestling <- list()
mean_years_height_M_Wrestling <- list()
sd_years_height_M_Wrestling <- list()
# women data
for (i in 1:length(data_Wrestling_F_year)) {
	mean_years_weight_F_Wrestling[[i]] <- mean(data_Wrestling_F_year[[i]]$Weight)
	sd_years_weight_F_Wrestling[[i]] <- sd(data_Wrestling_F_year[[i]]$Weight)
	mean_years_height_F_Wrestling[[i]] <- mean(data_Wrestling_F_year[[i]]$Height)
	sd_years_height_F_Wrestling[[i]] <- sd(data_Wrestling_F_year[[i]]$Height)
}
# men data
for (i in 1:length(data_Wrestling_M_year)) {
	mean_years_weight_M_Wrestling[[i]] <- mean(data_Wrestling_M_year[[i]]$Weight)
	sd_years_weight_M_Wrestling[[i]] <- sd(data_Wrestling_M_year[[i]]$Weight)
	mean_years_height_M_Wrestling[[i]] <- mean(data_Wrestling_M_year[[i]]$Height)
	sd_years_height_M_Wrestling[[i]] <- sd(data_Wrestling_M_year[[i]]$Height)
}
# make data frames
Wrestling_F_data <- do.call(rbind, Map(data.frame, Year = years_F_Wrestling, Mean_Weight = mean_years_weight_F_Wrestling, StdDev_Weight = sd_years_weight_F_Wrestling, Mean_Height = mean_years_height_F_Wrestling, StdDev_Height = sd_years_height_F_Wrestling))
Wrestling_M_data <- do.call(rbind, Map(data.frame, Year = years_M_Wrestling, Mean_Weight = mean_years_weight_F_Wrestling, StdDev_Weight = sd_years_weight_F_Wrestling, Mean_Height = mean_years_height_F_Wrestling, StdDev_Height = sd_years_height_F_Wrestling))
```

```{r overtime_plots, echo=F}
# women
plot(Swimming_F_data$Year, Swimming_F_data$Mean_Weight, xlab = "Year", ylab = "Weight [kg]", main = "Scatterplot of avg. Female Olympic Athletes' weights [kg] over time", pch=20, ylim = c(40,80), bty='L')
points(Rowing_F_data$Year, Rowing_F_data$Mean_Weight, pch = 20, col = "red")
points(Ice.Hockey_F_data$Year, Ice.Hockey_F_data$Mean_Weight, pch = 20, col = "pink")
points(Hockey_F_data$Year, Hockey_F_data$Mean_Weight, pch = 20, col = "coral")
points(Gymnastics_F_data$Year, Gymnastics_F_data$Mean_Weight, pch = 20, col = "orange")
points(Fencing_F_data$Year, Fencing_F_data$Mean_Weight, pch = 20, col = "gold")
points(Football_F_data$Year, Football_F_data$Mean_Weight, pch = 20, col = "green")
points(Canoeing_F_data$Year, Canoeing_F_data$Mean_Weight, pch = 20, col = "lightseagreen")
points(Basketball_F_data$Year, Basketball_F_data$Mean_Weight, pch = 20, col = "blue")
points(Wrestling_F_data$Year, Wrestling_F_data$Mean_Weight, pch = 20, col = "purple")
legend("bottomleft", c("Swimming", "Rowing", "Ice Hockey", "Hockey", "Gymnastics", "Fencing", "Football", "Canoeing", "Basketball", "Wrestling"), fill=c("black", "red", "pink", "coral", "orange", "gold", "green", "lightseagreen", "blue", "purple"))
# men
plot(Swimming_M_data$Year, Swimming_M_data$Mean_Weight, xlab = "Year", ylab = "Weight [kg]", main = "Scatterplot of avg. Male Olympic Athletes' weights [kg] over time", pch=20, ylim = c(40,80), bty='L')
points(Rowing_M_data$Year, Rowing_M_data$Mean_Weight, pch = 20, col = "red")
points(Ice.Hockey_M_data$Year, Ice.Hockey_M_data$Mean_Weight, pch = 20, col = "pink")
points(Hockey_M_data$Year, Hockey_M_data$Mean_Weight, pch = 20, col = "coral")
points(Gymnastics_M_data$Year, Gymnastics_M_data$Mean_Weight, pch = 20, col = "orange")
points(Fencing_M_data$Year, Fencing_M_data$Mean_Weight, pch = 20, col = "gold")
points(Football_M_data$Year, Football_M_data$Mean_Weight, pch = 20, col = "green")
points(Canoeing_M_data$Year, Canoeing_M_data$Mean_Weight, pch = 20, col = "lightseagreen")
points(Basketball_M_data$Year, Basketball_M_data$Mean_Weight, pch = 20, col = "blue")
points(Wrestling_M_data$Year, Wrestling_M_data$Mean_Weight, pch = 20, col = "purple")
legend("bottomleft", c("Swimming", "Rowing", "Ice Hockey", "Hockey", "Gymnastics", "Fencing", "Football", "Canoeing", "Basketball", "Wrestling"), fill=c("black", "red", "pink", "coral", "orange", "gold", "green", "lightseagreen", "blue", "purple"))
```

```{r testggplot, echo=F}
# women weight
women_weight_plot <- ggplot(Swimming_F_data, aes(x=Year, y=Mean_Weight)) + geom_point() + labs(title="Scatterplot of Olympic Women's Average Weights [kg] Over Time", x="year", y="weight [kg]") + geom_point(data = Rowing_F_data, colour='red') + geom_point(data = Ice.Hockey_F_data, colour='pink') + geom_point(data = Hockey_F_data, colour='coral') + geom_point(data = Gymnastics_F_data, colour='orange') + geom_point(data = Fencing_F_data, colour='gold') + geom_point(data = Football_F_data, colour='green') + geom_point(data = Canoeing_F_data, colour='lightseagreen') + geom_point(data = Basketball_F_data, colour='blue') + geom_point(data = Wrestling_F_data, colour='purple') + theme_minimal() + theme(axis.text.x = element_text(angle = 90, vjust = 1, size = 12, hjust = 1), axis.text.y = element_text(vjust = 1, size = 12, hjust = 1))
# women height
women_height_plot <- ggplot(Swimming_F_data, aes(x=Year, y=Mean_Height)) + geom_point() + labs(title="Scatterplot of Olympic Women's Average Heights [cm] Over Time", x="year", y="height [cm]") + geom_point(data = Rowing_F_data, colour='red') + geom_point(data = Ice.Hockey_F_data, colour='pink') + geom_point(data = Hockey_F_data, colour='coral') + geom_point(data = Gymnastics_F_data, colour='orange') + geom_point(data = Fencing_F_data, colour='gold') + geom_point(data = Football_F_data, colour='green') + geom_point(data = Canoeing_F_data, colour='lightseagreen') + geom_point(data = Basketball_F_data, colour='blue') + geom_point(data = Wrestling_F_data, colour='purple') + theme_minimal() + theme(axis.text.x = element_text(angle = 90, vjust = 1, size = 12, hjust = 1), axis.text.y = element_text(vjust = 1, size = 12, hjust = 1))
# men weight
men_weight_plot <- ggplot(Swimming_M_data, aes(x=Year, y=Mean_Weight)) + geom_point() + labs(title="Scatterplot of Olympic Men's Average Weights [kg] Over Time", x="year", y="weight [kg]") + geom_point(data = Rowing_M_data, colour='red') + geom_point(data = Ice.Hockey_M_data, colour='pink') + geom_point(data = Hockey_M_data, colour='coral') + geom_point(data = Gymnastics_M_data, colour='orange') + geom_point(data = Fencing_M_data, colour='gold') + geom_point(data = Football_M_data, colour='green') + geom_point(data = Canoeing_M_data, colour='lightseagreen') + geom_point(data = Basketball_M_data, colour='blue') + geom_point(data = Wrestling_M_data, colour='purple') + theme_minimal() + theme(axis.text.x = element_text(angle = 90, vjust = 1, size = 12, hjust = 1), axis.text.y = element_text(vjust = 1, size = 12, hjust = 1))
# men height
men_height_plot <- ggplot(Swimming_M_data, aes(x=Year, y=Mean_Height)) + geom_point() + labs(title="Scatterplot of Olympic Men's Average Heights [cm] Over Time", x="year", y="height [cm]") + geom_point(data = Rowing_M_data, colour='red') + geom_point(data = Ice.Hockey_M_data, colour='pink') + geom_point(data = Hockey_M_data, colour='coral') + geom_point(data = Gymnastics_M_data, colour='orange') + geom_point(data = Fencing_M_data, colour='gold') + geom_point(data = Football_M_data, colour='green') + geom_point(data = Canoeing_M_data, colour='lightseagreen') + geom_point(data = Basketball_M_data, colour='blue') + geom_point(data = Wrestling_M_data, colour='purple') + theme_minimal() + theme(axis.text.x = element_text(angle = 90, vjust = 1, size = 12, hjust = 1), axis.text.y = element_text(vjust = 1, size = 12, hjust = 1))
# plots
women_weight_plot
women_height_plot
men_weight_plot
men_height_plot
```


```{r ggplots, echo=F}
# Swimming
plot_F_weight_Swimming <- ggplot(Swimming_F_data, aes(x=Year, y=Mean_Weight)) + geom_point(size=2, shape=23, color='red') + labs(title="Scatterplot of Swimming Women Weights Over Time", x="year", y="weight [kg]") + geom_errorbar(aes(ymin = Mean_Weight-StdDev_Weight, ymax = Mean_Weight+StdDev_Weight), width=.2, position=position_dodge(0.05)) + theme(axis.text.x = element_text(angle = 90, vjust = 1, size = 12, hjust = 1), axis.text.y = element_text(vjust = 1, size = 12, hjust = 1))
plot_F_height_Swimming <- ggplot(Swimming_F_data, aes(x=Year, y=Mean_Height)) + geom_point(size=2, shape=23, color='blue') + labs(title="Scatterplot of Swimming Women Heights Over Time", x="year", y="height [cm]") + geom_errorbar(aes(ymin = Mean_Height-StdDev_Height, ymax = Mean_Height+StdDev_Height), width=.2, position=position_dodge(0.05)) + theme(axis.text.x = element_text(angle = 90, vjust = 1, size = 12, hjust = 1), axis.text.y = element_text(vjust = 1, size = 12, hjust = 1))
grid.arrange(plot_F_weight_Swimming, plot_F_height_Swimming, ncol=2, nrow=1)

plot_M_weight_Swimming <- ggplot(Swimming_M_data, aes(x=Year, y=Mean_Weight)) + geom_point(size=2, shape=23, color='green') + labs(title="Scatterplot of Swimming Men Weights Over Time", x="year", y="weight [kg]") + geom_errorbar(aes(ymin = Mean_Weight-StdDev_Weight, ymax = Mean_Weight+StdDev_Weight), width=.2, position=position_dodge(0.05)) + theme(axis.text.x = element_text(angle = 90, vjust = 1, size = 12, hjust = 1), axis.text.y = element_text(vjust = 1, size = 12, hjust = 1))
plot_M_height_Swimming <- ggplot(Swimming_M_data, aes(x=Year, y=Mean_Height)) + geom_point(size=2, shape=23, color='purple') + labs(title="Scatterplot of Swimming Men Heights Over Time", x="year", y="height [cm]") + geom_errorbar(aes(ymin = Mean_Height-StdDev_Height, ymax = Mean_Height+StdDev_Height), width=.2, position=position_dodge(0.05)) + theme(axis.text.x = element_text(angle = 90, vjust = 1, size = 12, hjust = 1), axis.text.y = element_text(vjust = 1, size = 12, hjust = 1))

grid.arrange(plot_M_weight_Swimming, plot_M_height_Swimming, ncol=2, nrow=1)

# Rowing
plot_F_weight_Rowing <- ggplot(Rowing_F_data, aes(x=Year, y=Mean_Weight)) + geom_point(size=2, shape=23, color='red') + labs(title="Scatterplot of Rowing Women Weights Over Time", x="year", y="weight [kg]") + geom_errorbar(aes(ymin = Mean_Weight-StdDev_Weight, ymax = Mean_Weight+StdDev_Weight), width=.2, position=position_dodge(0.05)) + theme(axis.text.x = element_text(angle = 90, vjust = 1, size = 12, hjust = 1), axis.text.y = element_text(vjust = 1, size = 12, hjust = 1))
plot_F_height_Rowing <- ggplot(Rowing_F_data, aes(x=Year, y=Mean_Height)) + geom_point(size=2, shape=23, color='blue') + labs(title="Scatterplot of Rowing Women Heights Over Time", x="year", y="height [cm]") + geom_errorbar(aes(ymin = Mean_Height-StdDev_Height, ymax = Mean_Height+StdDev_Height), width=.2, position=position_dodge(0.05)) + theme(axis.text.x = element_text(angle = 90, vjust = 1, size = 12, hjust = 1), axis.text.y = element_text(vjust = 1, size = 12, hjust = 1))
grid.arrange(plot_F_weight_Rowing, plot_F_height_Rowing, ncol=2, nrow=1)

plot_M_weight_Rowing <- ggplot(Rowing_M_data, aes(x=Year, y=Mean_Weight)) + geom_point(size=2, shape=23, color='green') + labs(title="Scatterplot of Rowing Men Weights Over Time", x="year", y="weight [kg]") + geom_errorbar(aes(ymin = Mean_Weight-StdDev_Weight, ymax = Mean_Weight+StdDev_Weight), width=.2, position=position_dodge(0.05)) + theme(axis.text.x = element_text(angle = 90, vjust = 1, size = 12, hjust = 1), axis.text.y = element_text(vjust = 1, size = 12, hjust = 1))
plot_M_height_Rowing <- ggplot(Rowing_M_data, aes(x=Year, y=Mean_Height)) + geom_point(size=2, shape=23, color='purple') + labs(title="Scatterplot of Rowing Men Heights Over Time", x="year", y="height [cm]") + geom_errorbar(aes(ymin = Mean_Height-StdDev_Height, ymax = Mean_Height+StdDev_Height), width=.2, position=position_dodge(0.05)) + theme(axis.text.x = element_text(angle = 90, vjust = 1, size = 12, hjust = 1), axis.text.y = element_text(vjust = 1, size = 12, hjust = 1))

grid.arrange(plot_M_weight_Rowing, plot_M_height_Rowing, ncol=2, nrow=1)

# Ice.Hockey
plot_F_weight_Ice.Hockey <- ggplot(Ice.Hockey_F_data, aes(x=Year, y=Mean_Weight)) + geom_point(size=2, shape=23, color='red') + labs(title="Scatterplot of Ice.Hockey Women Weights Over Time", x="year", y="weight [kg]") + geom_errorbar(aes(ymin = Mean_Weight-StdDev_Weight, ymax = Mean_Weight+StdDev_Weight), width=.2, position=position_dodge(0.05)) + theme(axis.text.x = element_text(angle = 90, vjust = 1, size = 12, hjust = 1), axis.text.y = element_text(vjust = 1, size = 12, hjust = 1))
plot_F_height_Ice.Hockey <- ggplot(Ice.Hockey_F_data, aes(x=Year, y=Mean_Height)) + geom_point(size=2, shape=23, color='blue') + labs(title="Scatterplot of Ice.Hockey Women Heights Over Time", x="year", y="height [cm]") + geom_errorbar(aes(ymin = Mean_Height-StdDev_Height, ymax = Mean_Height+StdDev_Height), width=.2, position=position_dodge(0.05)) + theme(axis.text.x = element_text(angle = 90, vjust = 1, size = 12, hjust = 1), axis.text.y = element_text(vjust = 1, size = 12, hjust = 1))
grid.arrange(plot_F_weight_Ice.Hockey, plot_F_height_Ice.Hockey, ncol=2, nrow=1)

plot_M_weight_Ice.Hockey <- ggplot(Ice.Hockey_M_data, aes(x=Year, y=Mean_Weight)) + geom_point(size=2, shape=23, color='green') + labs(title="Scatterplot of Ice.Hockey Men Weights Over Time", x="year", y="weight [kg]") + geom_errorbar(aes(ymin = Mean_Weight-StdDev_Weight, ymax = Mean_Weight+StdDev_Weight), width=.2, position=position_dodge(0.05)) + theme(axis.text.x = element_text(angle = 90, vjust = 1, size = 12, hjust = 1), axis.text.y = element_text(vjust = 1, size = 12, hjust = 1))
plot_M_height_Ice.Hockey <- ggplot(Ice.Hockey_M_data, aes(x=Year, y=Mean_Height)) + geom_point(size=2, shape=23, color='purple') + labs(title="Scatterplot of Ice.Hockey Men Heights Over Time", x="year", y="height [cm]") + geom_errorbar(aes(ymin = Mean_Height-StdDev_Height, ymax = Mean_Height+StdDev_Height), width=.2, position=position_dodge(0.05)) + theme(axis.text.x = element_text(angle = 90, vjust = 1, size = 12, hjust = 1), axis.text.y = element_text(vjust = 1, size = 12, hjust = 1))

grid.arrange(plot_M_weight_Ice.Hockey, plot_M_height_Ice.Hockey, ncol=2, nrow=1)

# Hockey
plot_F_weight_Hockey <- ggplot(Hockey_F_data, aes(x=Year, y=Mean_Weight)) + geom_point(size=2, shape=23, color='red') + labs(title="Scatterplot of Hockey Women Weights Over Time", x="year", y="weight [kg]") + geom_errorbar(aes(ymin = Mean_Weight-StdDev_Weight, ymax = Mean_Weight+StdDev_Weight), width=.2, position=position_dodge(0.05)) + theme(axis.text.x = element_text(angle = 90, vjust = 1, size = 12, hjust = 1), axis.text.y = element_text(vjust = 1, size = 12, hjust = 1))
plot_F_height_Hockey <- ggplot(Hockey_F_data, aes(x=Year, y=Mean_Height)) + geom_point(size=2, shape=23, color='blue') + labs(title="Scatterplot of Hockey Women Heights Over Time", x="year", y="height [cm]") + geom_errorbar(aes(ymin = Mean_Height-StdDev_Height, ymax = Mean_Height+StdDev_Height), width=.2, position=position_dodge(0.05)) + theme(axis.text.x = element_text(angle = 90, vjust = 1, size = 12, hjust = 1), axis.text.y = element_text(vjust = 1, size = 12, hjust = 1))
grid.arrange(plot_F_weight_Hockey, plot_F_height_Hockey, ncol=2, nrow=1)

plot_M_weight_Hockey <- ggplot(Hockey_M_data, aes(x=Year, y=Mean_Weight)) + geom_point(size=2, shape=23, color='green') + labs(title="Scatterplot of Hockey Men Weights Over Time", x="year", y="weight [kg]") + geom_errorbar(aes(ymin = Mean_Weight-StdDev_Weight, ymax = Mean_Weight+StdDev_Weight), width=.2, position=position_dodge(0.05)) + theme(axis.text.x = element_text(angle = 90, vjust = 1, size = 12, hjust = 1), axis.text.y = element_text(vjust = 1, size = 12, hjust = 1))
plot_M_height_Hockey <- ggplot(Hockey_M_data, aes(x=Year, y=Mean_Height)) + geom_point(size=2, shape=23, color='purple') + labs(title="Scatterplot of Hockey Men Heights Over Time", x="year", y="height [cm]") + geom_errorbar(aes(ymin = Mean_Height-StdDev_Height, ymax = Mean_Height+StdDev_Height), width=.2, position=position_dodge(0.05)) + theme(axis.text.x = element_text(angle = 90, vjust = 1, size = 12, hjust = 1), axis.text.y = element_text(vjust = 1, size = 12, hjust = 1))

grid.arrange(plot_M_weight_Hockey, plot_M_height_Hockey, ncol=2, nrow=1)

# Gymnastics
plot_F_weight_Gymnastics <- ggplot(Gymnastics_F_data, aes(x=Year, y=Mean_Weight)) + geom_point(size=2, shape=23, color='red') + labs(title="Scatterplot of Gymnastics Women Weights Over Time", x="year", y="weight [kg]") + geom_errorbar(aes(ymin = Mean_Weight-StdDev_Weight, ymax = Mean_Weight+StdDev_Weight), width=.2, position=position_dodge(0.05)) + theme(axis.text.x = element_text(angle = 90, vjust = 1, size = 12, hjust = 1), axis.text.y = element_text(vjust = 1, size = 12, hjust = 1))
plot_F_height_Gymnastics <- ggplot(Gymnastics_F_data, aes(x=Year, y=Mean_Height)) + geom_point(size=2, shape=23, color='blue') + labs(title="Scatterplot of Gymnastics Women Heights Over Time", x="year", y="height [cm]") + geom_errorbar(aes(ymin = Mean_Height-StdDev_Height, ymax = Mean_Height+StdDev_Height), width=.2, position=position_dodge(0.05)) + theme(axis.text.x = element_text(angle = 90, vjust = 1, size = 12, hjust = 1), axis.text.y = element_text(vjust = 1, size = 12, hjust = 1))
grid.arrange(plot_F_weight_Gymnastics, plot_F_height_Gymnastics, ncol=2, nrow=1)

plot_M_weight_Gymnastics <- ggplot(Gymnastics_M_data, aes(x=Year, y=Mean_Weight)) + geom_point(size=2, shape=23, color='green') + labs(title="Scatterplot of Gymnastics Men Weights Over Time", x="year", y="weight [kg]") + geom_errorbar(aes(ymin = Mean_Weight-StdDev_Weight, ymax = Mean_Weight+StdDev_Weight), width=.2, position=position_dodge(0.05)) + theme(axis.text.x = element_text(angle = 90, vjust = 1, size = 12, hjust = 1), axis.text.y = element_text(vjust = 1, size = 12, hjust = 1))
plot_M_height_Gymnastics <- ggplot(Gymnastics_M_data, aes(x=Year, y=Mean_Height)) + geom_point(size=2, shape=23, color='purple') + labs(title="Scatterplot of Gymnastics Men Heights Over Time", x="year", y="height [cm]") + geom_errorbar(aes(ymin = Mean_Height-StdDev_Height, ymax = Mean_Height+StdDev_Height), width=.2, position=position_dodge(0.05)) + theme(axis.text.x = element_text(angle = 90, vjust = 1, size = 12, hjust = 1), axis.text.y = element_text(vjust = 1, size = 12, hjust = 1))

grid.arrange(plot_M_weight_Gymnastics, plot_M_height_Gymnastics, ncol=2, nrow=1)

# Fencing
plot_F_weight_Fencing <- ggplot(Fencing_F_data, aes(x=Year, y=Mean_Weight)) + geom_point(size=2, shape=23, color='red') + labs(title="Scatterplot of Fencing Women Weights Over Time", x="year", y="weight [kg]") + geom_errorbar(aes(ymin = Mean_Weight-StdDev_Weight, ymax = Mean_Weight+StdDev_Weight), width=.2, position=position_dodge(0.05)) + theme(axis.text.x = element_text(angle = 90, vjust = 1, size = 12, hjust = 1), axis.text.y = element_text(vjust = 1, size = 12, hjust = 1))
plot_F_height_Fencing <- ggplot(Fencing_F_data, aes(x=Year, y=Mean_Height)) + geom_point(size=2, shape=23, color='blue') + labs(title="Scatterplot of Fencing Women Heights Over Time", x="year", y="height [cm]") + geom_errorbar(aes(ymin = Mean_Height-StdDev_Height, ymax = Mean_Height+StdDev_Height), width=.2, position=position_dodge(0.05)) + theme(axis.text.x = element_text(angle = 90, vjust = 1, size = 12, hjust = 1), axis.text.y = element_text(vjust = 1, size = 12, hjust = 1))
grid.arrange(plot_F_weight_Fencing, plot_F_height_Fencing, ncol=2, nrow=1)

plot_M_weight_Fencing <- ggplot(Fencing_M_data, aes(x=Year, y=Mean_Weight)) + geom_point(size=2, shape=23, color='green') + labs(title="Scatterplot of Fencing Men Weights Over Time", x="year", y="weight [kg]") + geom_errorbar(aes(ymin = Mean_Weight-StdDev_Weight, ymax = Mean_Weight+StdDev_Weight), width=.2, position=position_dodge(0.05)) + theme(axis.text.x = element_text(angle = 90, vjust = 1, size = 12, hjust = 1), axis.text.y = element_text(vjust = 1, size = 12, hjust = 1))
plot_M_height_Fencing <- ggplot(Fencing_M_data, aes(x=Year, y=Mean_Height)) + geom_point(size=2, shape=23, color='purple') + labs(title="Scatterplot of Fencing Men Heights Over Time", x="year", y="height [cm]") + geom_errorbar(aes(ymin = Mean_Height-StdDev_Height, ymax = Mean_Height+StdDev_Height), width=.2, position=position_dodge(0.05)) + theme(axis.text.x = element_text(angle = 90, vjust = 1, size = 12, hjust = 1), axis.text.y = element_text(vjust = 1, size = 12, hjust = 1))

grid.arrange(plot_M_weight_Fencing, plot_M_height_Fencing, ncol=2, nrow=1)

# Football
plot_F_weight_Football <- ggplot(Football_F_data, aes(x=Year, y=Mean_Weight)) + geom_point(size=2, shape=23, color='red') + labs(title="Scatterplot of Football Women Weights Over Time", x="year", y="weight [kg]") + geom_errorbar(aes(ymin = Mean_Weight-StdDev_Weight, ymax = Mean_Weight+StdDev_Weight), width=.2, position=position_dodge(0.05)) + theme(axis.text.x = element_text(angle = 90, vjust = 1, size = 12, hjust = 1), axis.text.y = element_text(vjust = 1, size = 12, hjust = 1))
plot_F_height_Football <- ggplot(Football_F_data, aes(x=Year, y=Mean_Height)) + geom_point(size=2, shape=23, color='blue') + labs(title="Scatterplot of Football Women Heights Over Time", x="year", y="height [cm]") + geom_errorbar(aes(ymin = Mean_Height-StdDev_Height, ymax = Mean_Height+StdDev_Height), width=.2, position=position_dodge(0.05)) + theme(axis.text.x = element_text(angle = 90, vjust = 1, size = 12, hjust = 1), axis.text.y = element_text(vjust = 1, size = 12, hjust = 1))
grid.arrange(plot_F_weight_Football, plot_F_height_Football, ncol=2, nrow=1)

plot_M_weight_Football <- ggplot(Football_M_data, aes(x=Year, y=Mean_Weight)) + geom_point(size=2, shape=23, color='green') + labs(title="Scatterplot of Football Men Weights Over Time", x="year", y="weight [kg]") + geom_errorbar(aes(ymin = Mean_Weight-StdDev_Weight, ymax = Mean_Weight+StdDev_Weight), width=.2, position=position_dodge(0.05)) + theme(axis.text.x = element_text(angle = 90, vjust = 1, size = 12, hjust = 1), axis.text.y = element_text(vjust = 1, size = 12, hjust = 1))
plot_M_height_Football <- ggplot(Football_M_data, aes(x=Year, y=Mean_Height)) + geom_point(size=2, shape=23, color='purple') + labs(title="Scatterplot of Football Men Heights Over Time", x="year", y="height [cm]") + geom_errorbar(aes(ymin = Mean_Height-StdDev_Height, ymax = Mean_Height+StdDev_Height), width=.2, position=position_dodge(0.05)) + theme(axis.text.x = element_text(angle = 90, vjust = 1, size = 12, hjust = 1), axis.text.y = element_text(vjust = 1, size = 12, hjust = 1))

grid.arrange(plot_M_weight_Football, plot_M_height_Football, ncol=2, nrow=1)

# Canoeing
plot_F_weight_Canoeing <- ggplot(Canoeing_F_data, aes(x=Year, y=Mean_Weight)) + geom_point(size=2, shape=23, color='red') + labs(title="Scatterplot of Canoeing Women Weights Over Time", x="year", y="weight [kg]") + geom_errorbar(aes(ymin = Mean_Weight-StdDev_Weight, ymax = Mean_Weight+StdDev_Weight), width=.2, position=position_dodge(0.05)) + theme(axis.text.x = element_text(angle = 90, vjust = 1, size = 12, hjust = 1), axis.text.y = element_text(vjust = 1, size = 12, hjust = 1))
plot_F_height_Canoeing <- ggplot(Canoeing_F_data, aes(x=Year, y=Mean_Height)) + geom_point(size=2, shape=23, color='blue') + labs(title="Scatterplot of Canoeing Women Heights Over Time", x="year", y="height [cm]") + geom_errorbar(aes(ymin = Mean_Height-StdDev_Height, ymax = Mean_Height+StdDev_Height), width=.2, position=position_dodge(0.05)) + theme(axis.text.x = element_text(angle = 90, vjust = 1, size = 12, hjust = 1), axis.text.y = element_text(vjust = 1, size = 12, hjust = 1))
grid.arrange(plot_F_weight_Canoeing, plot_F_height_Canoeing, ncol=2, nrow=1)

plot_M_weight_Canoeing <- ggplot(Canoeing_M_data, aes(x=Year, y=Mean_Weight)) + geom_point(size=2, shape=23, color='green') + labs(title="Scatterplot of Canoeing Men Weights Over Time", x="year", y="weight [kg]") + geom_errorbar(aes(ymin = Mean_Weight-StdDev_Weight, ymax = Mean_Weight+StdDev_Weight), width=.2, position=position_dodge(0.05)) + theme(axis.text.x = element_text(angle = 90, vjust = 1, size = 12, hjust = 1), axis.text.y = element_text(vjust = 1, size = 12, hjust = 1))
plot_M_height_Canoeing <- ggplot(Canoeing_M_data, aes(x=Year, y=Mean_Height)) + geom_point(size=2, shape=23, color='purple') + labs(title="Scatterplot of Canoeing Men Heights Over Time", x="year", y="height [cm]") + geom_errorbar(aes(ymin = Mean_Height-StdDev_Height, ymax = Mean_Height+StdDev_Height), width=.2, position=position_dodge(0.05)) + theme(axis.text.x = element_text(angle = 90, vjust = 1, size = 12, hjust = 1), axis.text.y = element_text(vjust = 1, size = 12, hjust = 1))

grid.arrange(plot_M_weight_Canoeing, plot_M_height_Canoeing, ncol=2, nrow=1)

# Basketball
plot_F_weight_Basketball <- ggplot(Basketball_F_data, aes(x=Year, y=Mean_Weight)) + geom_point(size=2, shape=23, color='red') + labs(title="Scatterplot of Basketball Women Weights Over Time", x="year", y="weight [kg]") + geom_errorbar(aes(ymin = Mean_Weight-StdDev_Weight, ymax = Mean_Weight+StdDev_Weight), width=.2, position=position_dodge(0.05)) + theme(axis.text.x = element_text(angle = 90, vjust = 1, size = 12, hjust = 1), axis.text.y = element_text(vjust = 1, size = 12, hjust = 1))
plot_F_height_Basketball <- ggplot(Basketball_F_data, aes(x=Year, y=Mean_Height)) + geom_point(size=2, shape=23, color='blue') + labs(title="Scatterplot of Basketball Women Heights Over Time", x="year", y="height [cm]") + geom_errorbar(aes(ymin = Mean_Height-StdDev_Height, ymax = Mean_Height+StdDev_Height), width=.2, position=position_dodge(0.05)) + theme(axis.text.x = element_text(angle = 90, vjust = 1, size = 12, hjust = 1), axis.text.y = element_text(vjust = 1, size = 12, hjust = 1))
grid.arrange(plot_F_weight_Basketball, plot_F_height_Basketball, ncol=2, nrow=1)

plot_M_weight_Basketball <- ggplot(Basketball_M_data, aes(x=Year, y=Mean_Weight)) + geom_point(size=2, shape=23, color='green') + labs(title="Scatterplot of Basketball Men Weights Over Time", x="year", y="weight [kg]") + geom_errorbar(aes(ymin = Mean_Weight-StdDev_Weight, ymax = Mean_Weight+StdDev_Weight), width=.2, position=position_dodge(0.05)) + theme(axis.text.x = element_text(angle = 90, vjust = 1, size = 12, hjust = 1), axis.text.y = element_text(vjust = 1, size = 12, hjust = 1))
plot_M_height_Basketball <- ggplot(Basketball_M_data, aes(x=Year, y=Mean_Height)) + geom_point(size=2, shape=23, color='purple') + labs(title="Scatterplot of Basketball Men Heights Over Time", x="year", y="height [cm]") + geom_errorbar(aes(ymin = Mean_Height-StdDev_Height, ymax = Mean_Height+StdDev_Height), width=.2, position=position_dodge(0.05)) + theme(axis.text.x = element_text(angle = 90, vjust = 1, size = 12, hjust = 1), axis.text.y = element_text(vjust = 1, size = 12, hjust = 1))

grid.arrange(plot_M_weight_Basketball, plot_M_height_Basketball, ncol=2, nrow=1)

# Wrestling
plot_F_weight_Wrestling <- ggplot(Wrestling_F_data, aes(x=Year, y=Mean_Weight)) + geom_point(size=2, shape=23, color='red') + labs(title="Scatterplot of Wrestling Women Weights Over Time", x="year", y="weight [kg]") + geom_errorbar(aes(ymin = Mean_Weight-StdDev_Weight, ymax = Mean_Weight+StdDev_Weight), width=.2, position=position_dodge(0.05)) + theme(axis.text.x = element_text(angle = 90, vjust = 1, size = 12, hjust = 1), axis.text.y = element_text(vjust = 1, size = 12, hjust = 1))
plot_F_height_Wrestling <- ggplot(Wrestling_F_data, aes(x=Year, y=Mean_Height)) + geom_point(size=2, shape=23, color='blue') + labs(title="Scatterplot of Wrestling Women Heights Over Time", x="year", y="height [cm]") + geom_errorbar(aes(ymin = Mean_Height-StdDev_Height, ymax = Mean_Height+StdDev_Height), width=.2, position=position_dodge(0.05)) + theme(axis.text.x = element_text(angle = 90, vjust = 1, size = 12, hjust = 1), axis.text.y = element_text(vjust = 1, size = 12, hjust = 1))
grid.arrange(plot_F_weight_Wrestling, plot_F_height_Wrestling, ncol=2, nrow=1)

plot_M_weight_Wrestling <- ggplot(Wrestling_M_data, aes(x=Year, y=Mean_Weight)) + geom_point(size=2, shape=23, color='green') + labs(title="Scatterplot of Wrestling Men Weights Over Time", x="year", y="weight [kg]") + geom_errorbar(aes(ymin = Mean_Weight-StdDev_Weight, ymax = Mean_Weight+StdDev_Weight), width=.2, position=position_dodge(0.05)) + theme(axis.text.x = element_text(angle = 90, vjust = 1, size = 12, hjust = 1), axis.text.y = element_text(vjust = 1, size = 12, hjust = 1))
plot_M_height_Wrestling <- ggplot(Wrestling_M_data, aes(x=Year, y=Mean_Height)) + geom_point(size=2, shape=23, color='purple') + labs(title="Scatterplot of Wrestling Men Heights Over Time", x="year", y="height [cm]") + geom_errorbar(aes(ymin = Mean_Height-StdDev_Height, ymax = Mean_Height+StdDev_Height), width=.2, position=position_dodge(0.05)) + theme(axis.text.x = element_text(angle = 90, vjust = 1, size = 12, hjust = 1), axis.text.y = element_text(vjust = 1, size = 12, hjust = 1))

grid.arrange(plot_M_weight_Wrestling, plot_M_height_Wrestling, ncol=2, nrow=1)
```



