---
title: "Olympics_EDA"
author: "LNT"
date: "1/31/2020"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r basicfcn, include=F}
loadPkg = function(x) { if (!require(x,character.only=T, quietly =T)) { install.packages(x,dep=T,repos="http://cran.us.r-project.org"); if(!require(x,character.only=T, quietly = T)) stop("Package not found") } }
```

```{r Q1, include=T}
# Load data
# 
athletes <- read.csv("athlete_events.csv") 

colnames(athletes)
loadPkg("dplyr")
loadPkg("ggplot2")

```
# Find the statistics (summary) of the heights, weights, and ages of all Olympic Athletes 

```{r HWA, echo=F} 

dim(athletes)
summary(athletes$Height)
summary(athletes$Weight)
summary(athletes$Age)
```

## Height 
# Gold, Silver and Bronze Medal Athletes
```{r Height, echo=F}

gold_medals <- subset(athletes, Medal == "Gold")
silver_medals <- subset(athletes, Medal == "Silver")
bronze_medals <- subset(athletes, Medal == "Bronze")

gold_medals[["bmi"]] <- (gold_medals$Weight/gold_medals$Height/gold_medals$Height) * 10000

silver_medals[["bmi"]] <- (silver_medals$Weight/silver_medals$Height/silver_medals$Height) * 10000

bronze_medals[["bmi"]] <- (bronze_medals$Weight/bronze_medals$Height/bronze_medals$Height) * 10000
summary(gold_medals$Height)
summary(silver_medals$Height)
summary(bronze_medals$Height)
```

# Weight
## Gold, Silver and Bronze Medal Athletes
```{r Weight, echo=F}
summary(gold_medals$Weight)
summary(silver_medals$Weight)
summary(bronze_medals$Weight)
```

# BMI 
## Gold, Silver and Bronze Medal Athletes
```{r BMI}
summary(gold_medals$bmi)
summary(silver_medals$bmi)
summary(bronze_medals$bmi)
```
```{r loading,echo=F}

```

## Gold Medal Athletes BMI
```{r gold, echo=F}

boxplot(gold_medals$bmi, main="Gold Medal Athletes BMI", ylab="weight (lbs)", col='gold')
hist(gold_medals$bmi, main="Gold Medal BMI", col = 'Gold' ) 

```
## Silver Medal Athletes BMI
```{r silver, echo =F}

boxplot(silver_medals$bmi, main="Silver Medal Athletes BMI", ylab="BMI", col='gray')
hist(silver_medals$bmi, main="Silver Medal Athletes BMI", col = 'gray' ) 
```
## Bronze Medal Athletes BMI
```{r bronze, echo=F}

boxplot(bronze_medals$bmi, main="Bronze Medal Athletes BMI", ylab="BMI", col='brown')

hist(bronze_medals$bmi, main="Bronze Medal Athletes BMI", col = 'brown' )
```
```{r scatter, echo=F}

summer_gold <-subset(gold_medals, gold_medals$Season == "Summer" & gold_medals$Sport %in% summer_sports)
winter_gold <- subset (gold_medals, gold_medals$Season == "Winter")



ggplot(data=summer_gold)+
  geom_point(mapping = aes(x=Weight, y=Height, color=Sport))+
  ggtitle("Scatter plot of Summer Gold Medalists Height vs Weight")

ggplot(data=winter_gold)+
  geom_point(mapping = aes(x=Weight, y=Height, color=Sport))
  ggtitle("Scatter plot of Winter Gold Medalists Height vs Weight")



```

# How do Olympic athletes with medals measure up in BMI?
```{r removeDups, echo=F}

medal_athletes <- subset(athletes, !is.na(Medal))
dim(medal_athletes)
medal_athletes[["BMI"]] <- (medal_athletes$Weight/gold_medals$Height/gold_medals$Height) * 10000



medal_athletes <- medal_athletes %>% mutate(Category = case_when(
  medal_athletes$BMI < 18.5 ~ "Underweight",
  medal_athletes$BMI >= 18.5 & medal_athletes$BMI < 25 ~ "Normal Weight",
  medal_athletes$BMI >= 25 & medal_athletes$BMI < 30 ~ "Overweight",
  TRUE ~ "Obese"
))

ggplot(data=medal_athletes, aes(x=Category, y=Age, fill=Sex))+ geom_boxplot()
                

df <- medal_athletes[,c("ID", "Category")]
df <- df %>% group_by(Category) %>% tally()

barplot(df$n, names.arg=c("Underweight", "Normal", "Overweight", "Obese"), col= "green")

g <- ggplot(medal_athletes, aes(x=Age, y=BMI, fill=Sex))

# Scatterplot
g + geom_point() + 
  geom_smooth(method="lm", se=F) +
  labs( 
       y="Age", 
       x="BMI", 
       title="Scatter plot of Age vs BMI")
```
```{r corr}
loadPkg("ggcorrplot")
df1 <- medal_athletes[,c("Age", "Height", "Weight", "BMI")]
df1 <- na.omit(df1)


# Correlation matrix
corr <- round(cor(df1), 1)

# Plot
ggcorrplot(corr, hc.order = TRUE, 
           type = "lower", 
           lab = TRUE, 
           #lab_size = 3, 
           method="circle", 
           title="medal_athletes", 
           ggtheme=theme_bw)


```
