---
title: "DATS 6101 Spring 2020 Olympic Data EDA"
author: "Izzy Illari"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document:
    theme: readable
    toc: true
    toc_float: yes
    toc_depth: '2'
    number_sections: false
    keep_tex: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = F, results = T, message = F)
options(scientific=T, digits = 3) 
```

```{r basicfcn, include=F}
loadPkg = function(x) { if (!require(x,character.only=T, quietly =T)) { install.packages(x,dep=T,repos="http://cran.us.r-project.org"); if(!require(x,character.only=T)) stop("Package not found") } }
# unload/detact package when done using it
```

```{r, echo=F}
#Data taken from https://www.kaggle.com/heesoo37/120-years-of-olympic-history-athletes-and-results
athlete_events <- data.frame(read.csv("/Users/iillari/Documents/gwu/spring2020/intro_dats/eda_project/120-years-of-olympic-history-athletes-and-results/athlete_events.csv"))
noc_regions <- data.frame(read.csv("/Users/iillari/Documents/gwu/spring2020/intro_dats/eda_project/120-years-of-olympic-history-athletes-and-results/noc_regions.csv"))
```

# Summary of data

Data from athlete_events.csv: 

```{r, echo=F}
summary(athlete_events)
```

Data from noc_regions.csv: 

```{r, echo=F}
summary(noc_regions)
```

# Year data

```{r, echo=F}
#wrangle data
athlete_events_noNA <- na.omit(athlete_events)
year_data <- na.omit(athlete_events$Year)
#data by year
data_2016 <- athlete_events_noNA[ athlete_events_noNA$Year == 2016, ]
data_2006 <- athlete_events_noNA[ athlete_events_noNA$Year == 2006, ]
data_1996 <- athlete_events_noNA[ athlete_events_noNA$Year == 1996, ]
#get rgb color data using console
#col2rgb(c("lightblue", "lightgreen", "pink"))
#transparent colors
light_blue <- rgb(173,216,230,max = 255, alpha = 80, names = "lt.blue")
pink <- rgb(255,192,203, max = 255, alpha = 80, names = "lt.pink")
light_green <- rgb(144,238,144, max = 255, alpha = 80, names = "lt.green")
#overlapping histograms
hist(data_2016$Weight, main= "Histogram of Olympic athlete's weights [kg] over time", xlab="weight [kg]", col = pink)
hist(data_2006$Weight, col = light_green, add=T)
hist(data_1996$Weight, col = light_blue, add=T)
legend("topright", c("2016", "2006", "1996"), fill=c(pink, light_green, light_blue))
box()
```

```{r, echo=F}
#create a list by years 
data_year <- split(athlete_events_noNA, athlete_events_noNA$Year)
```



